### ISSUE TITLE
MegaLogger.getLogger() inconsistency.

### ISSUE THREAD

**Issue by diegocr** [meganz/megalogger#2]
There is a problem when using `MegaLogger.getLogger()` and the provided `parentLogger` is different to one previously used.

For example:

``` js
var writeLogger = MegaLogger.getLogger('writer');
var readLogger = MegaLogger.getLogger('read');

function readIO() {
   var logger = MegaLogger.getLogger('I/O', {}, readLogger);
   logger.info('IO', arguments);
}

function writeIO() {
   var logger = MegaLogger.getLogger('I/O', {}, writeLogger);
   logger.info('IO', arguments);
}

readIO();
writeIO();
```

Both logger calls will output:

``` bash
2015-6-12 21:9:4.161 - read:I/O - INFO IO Arguments { , 2 more… }
2015-6-12 21:9:4.162 - read:I/O - INFO IO Arguments { , 2 more… }
```

I think the way `MegaLogger` instaces are stored into `_logRegistry` must include the full/recursive path to the parentLogger, if any provided.

**Comment by infinity0** [comment]
Yeah, this API design around the "parent" logger was not very nice. Most logging frameworks make you specify a path like "writer.IO" as the name, and use this to implicitly find the parent logger. I think we should switch to this sort of naming. Wondering what @lpetrov thinks about it.

(Also, what were the other options on JS logging frameworks, and why didn't we choose those?)

**Comment by lpetrov** [comment]
The original idea, was that there is a "root" logger, which contains all child ones, as nodes, in a tree.
So basically, it should had been initialised as a getLogger() (no logger name, which implies that this is the root logger) and from there on, all loggers should point to that logger as a reference.
However, this was not efficient, especially when writing tests.

So me and Guy ended up with this, auto initialise/default root "logger" trick, which should initialise a default logger if a root/default one is not yet initialised and made the parentLogger argument, optional.

---

Regarding the example above, the API was designed to auto initialise loggers (child ones too) and cache them in the log registry.
So, the "name" should be a unique string, which, once initialised for a logger, will NOT re-initialize OR change the parent logger.
What i typically do, is to have a ""namespace"" for loggers, as @infinity0 mentioned - "package:module" (but with ":").
So, the example code is working as expected. The second getLogger() call is trying to re-initialise already initialised (with diff. parent logger - "read")  logger.

---

Regarding the other libraries.... they are either meant to be used in nodejs, which means they have tons of code to handle streams/IO/events/etc OR for the browser, but provides custom UI for browsing logs (using HTML+CSS, which is a total overhead).
What we needed was a very simple logger, based on top of the console.\* "interface" (both UI and API), but with a way to prefix the logged messages, so that we can filter easily the output, without needing to manually prefix ALL console.log/error/etc calls.
As a bonus, we have options to filter using regexps in the code, change the output functions (in case we want to use different transport layer in the future) and colors, to easily see in the web dev console what is what, when using console.error.
The console.error is a special case. I often switch the console.\* calls to -> console.error to get more debug data (stack traces!), which, when using the MegaLogger will still output some colors so that you can differentiate between real errors and debug calls, despite that ALL logs are outputed using console.error. :)
And one last thing, our logger is meant to be (very) simple, dummy and not validate the "name" attribute or do "magic", but in the end it is 420 LOC (incl. comments!), which compared to the other solutions, for use in a browser environment is a major difference/improvement :)

**Comment by diegocr** [comment]
> So, the "name" should be a unique string, which, once initialised for a logger, will NOT re-initialize OR change the parent logger. (...) So, the example code is working as expected. The second getLogger() call is trying to re-initialise already initialised (with diff. parent logger - "read") logger.

I see, sad it is working as expected, that is only showing a weakness of the lib :)

Not a big deal in any case, i just replaced `getLogger` by `new MegaLogger` in the affected classes.
